CREATE TABLE pessoa(
	codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL,
	ativo BIT(1) NOT NULL,
	logradouro VARCHAR(50) NULL,
	numero VARCHAR(10) NULL,
	complemento VARCHAR(30) NULL,
	bairro VARCHAR(20) NULL,
	cep VARCHAR(10) NULL,
	cidade VARCHAR(10) NULL,
	estado VARCHAR(2) NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

